name: Build Container
on:
  push:
    branches:
      - main
    paths:
      - 'src/FE/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login container
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} ${{ vars.DOCKER_REGISTRY }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container
        run: |
          cd src/FE && docker build -t chats .

      - name: Tag container with latest and run number
        run: |
          docker tag chats ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker tag chats ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:latest
          
      - name: Push container
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:latest
          
  deploy-dev-stg:
    needs: build-container
    uses: ./.github/workflows/deploy.yml
    with:
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}