name: Build Container
on:
  push:
    branches:
      - main
    paths:
      - 'src/FE/**'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login container
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_REGISTRY }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container
        run: |
          cd src/FE
          docker build -t chats .

      - name: Tag container with latest and run number
        run: |
          docker tag chats ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker tag chats ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats:latest
          
      - name: Push container
        run: |
          DATE=$(date +'%Y%m%d')
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats:latest

      - name: Save FRONTEND_VERSION
        run: echo "r-${{ github.run_number }}" > FRONTEND_VERSION.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-version
          path: FRONTEND_VERSION.txt