name: Build Container
on:
  push:
    branches:
      - main
    paths:
      - 'src/BE/**'
      - 'src/FE/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login container
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} ${{ vars.DOCKER_REGISTRY }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend
        run: |
          cd ./src/FE
          npm i
          npm run build
          mv ./out/* ../BE/wwwroot

      - name: Build container
        run: |
          dotnet publish ./src/BE/Chats.BE.csproj -c Release --os linux --arch x64 /t:PublishContainer /p:ContainerRepository=chats

      - name: Tag container with 'latest' & run number
        run: |
          docker tag chats ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker tag chats ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:latest
          
      - name: Push container
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:latest

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: r-${{ github.run_number }}
          release_name: r-${{ github.run_number }}
          draft: false
          prerelease: false

      - name: build win-x64 binary
        run: |
          rm -rf ./Publish
          dotnet publish ./src/BE/Chats.BE.csproj -c Release -r win-x64 --self-contained true -o ./Publish /p:DeleteExistingFiles=True /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:EnableCompressionInSingleFile=true
          7z a -tzip -mx=1 chats-win-x64-r${{ github.run_number }}.zip ./Publish/*

      - name: Upload win-x64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chats-win-x64-r${{ github.run_number }}.zip
          asset_name: chats-win-x64-r${{ github.run_number }}.zip
          asset_content_type: application/octet-stream

      - name: build linux-x64 binary
        run: |
          rm -rf ./Publish
          dotnet publish ./src/BE/Chats.BE.csproj -c Release -r linux-x64 --self-contained true -o ./Publish /p:DeleteExistingFiles=True /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:EnableCompressionInSingleFile=true
          7z a -tzip -mx=1 chats-linux-x64-r${{ github.run_number }}.zip ./Publish/*

      - name: Upload linux-x64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chats-linux-x64-r${{ github.run_number }}.zip
          asset_name: chats-linux-x64-r${{ github.run_number }}.zip
          asset_content_type: application/octet-stream

      - name: build linux-arm64 binary
        run: |
          rm -rf ./Publish
          dotnet publish ./src/BE/Chats.BE.csproj -c Release -r linux-arm64 --self-contained true -o ./Publish /p:DeleteExistingFiles=True /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:EnableCompressionInSingleFile=true
          7z a -tzip -mx=1 chats-linux-arm64-r${{ github.run_number }}.zip ./Publish/*

      - name: Upload linux-arm64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chats-linux-arm64-r${{ github.run_number }}.zip
          asset_name: chats-linux-arm64-r${{ github.run_number }}.zip
          asset_content_type: application/octet-stream

  deploy-dev-stg:
    needs: build-container
    uses: ./.github/workflows/deploy.yml
    with:
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}
      TAG: r-${{ github.run_number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}