name: Build Container
on:
  push:
    branches:
      - main
    paths:
      - 'src/BE/**'
      - 'src/FE/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('src/FE/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install dependencies
        working-directory: ./src/FE
        run: npm ci

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: src/FE/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.svg', '**/*.png', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-next-cache-

      - name: Build frontend
        working-directory: ./src/FE
        run: npm run build

      - name: Upload FE build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chats-fe
          path: ./src/FE/out

  build-container:
    needs: build-fe
    runs-on: ubuntu-latest
    steps:
      - name: Login container
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} ${{ vars.DOCKER_REGISTRY }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download FE build artifacts
        uses: actions/download-artifact@v4
        with:
          name: chats-fe
          path: ./src/BE/wwwroot

      - name: Build container
        run: |
          dotnet publish ./src/BE/Chats.BE.csproj -c Release --os linux --arch x64 /t:PublishContainer /p:ContainerRepository=chats

      - name: Tag container with 'latest' & run number
        run: |
          docker tag chats ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker tag chats ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:latest
          
      - name: Push container
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:latest

  build-binaries:
    needs: build-fe
    strategy:
      matrix:
        include:
          - runtime: win-x64
          - runtime: linux-x64
          - runtime: linux-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download FE build artifacts
        uses: actions/download-artifact@v4
        with:
          name: chats-fe
          path: ./src/BE/wwwroot

      - name: build binary
        run: |
          dotnet publish ./src/BE/Chats.BE.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -o ./Publish /p:DeleteExistingFiles=True /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:EnableCompressionInSingleFile=true

      - name: Archive binary
        run: |
          7z a -tzip -mx=1 chats-win-x64.zip ./Publish/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chats-${{ matrix.runtime }}
          path: ./Publish

  create-release:
    needs: [build-container, build-binaries]
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.release_id }}
    steps:
      - name: Get latest tag
        id: get_latest_tag
        uses: actions/github-script@v7
        with:
          script: |
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            if (tags.length === 0) {
              return { latestTag: "" };
            }
            return { latestTag: tags[0].name };
          result-encoding: string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/github-script@v6
        with:
          script: |
            const latestTag = "${{ steps.get_latest_tag.outputs.latestTag }}";
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `r-${{ github.run_number }}`,
              name: `r-${{ github.run_number }}`,
              body: `**Docker Download**: \`docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}\`
                    **Full Changelog**: https://github.com/sdcb/chats/compare/${latestTag}...r-${{ github.run_number }}`,
              draft: false,
              prerelease: false,
            });
            core.setOutput('release_id', response.data.id);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release-assets:
    strategy:
      matrix:
        include:
          - asset: chats-win-x64
          - asset: chats-linux-x64
          - asset: chats-linux-arm64
          - asset: chats-fe
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.asset }}
          path: ${{ matrix.asset }}
  
      - name: Compress artifacts into ZIP
        run: |
          zip -r ${{ matrix.asset }}.zip ${{ matrix.asset }}
        shell: bash
  
      - name: Upload Asset
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const assetPath = './${{ matrix.asset }}.zip';
            const releaseId = "${{ needs.create-release.outputs.release_id }}";
            const asset = fs.readFileSync(assetPath);

            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              name: '${{ matrix.asset }}.zip',
              data: asset,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev-stg:
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploy dev/stg
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 zhoujie@home.starworks.cc << 'EOF'
            docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/chats:r-${{ github.run_number }}
            cd chats
            sed -i "s/^TAG=.*/TAG=r-${{ github.run_number }}/" ~/chats/dev.env
            sed -i "s/^TAG=.*/TAG=r-${{ github.run_number }}/" ~/chats/stg.env
            ./dev.sh && ./stg.sh
            