name: Build BE Container
on:
  push:
    branches:
      - main
    paths:
      - 'src/BE/**'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login container
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_REGISTRY }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container
        run: |
          docker build -t chats . -f src/BE/Dockerfile

      - name: Tag container with 'latest' & run number
        run: |
          docker tag chats ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats-be:r-${{ github.run_number }}
          docker tag chats ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats-be:latest
          
      - name: Push container
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats-be:r-${{ github.run_number }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats-be:latest

      - name: Save BACKEND_VERSION
        run: echo "BACKEND_VERSION=r-${{ github.run_number }}" > BACKEND_VERSION.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-version
          path: BACKEND_VERSION.txt