name: Deploy

on:
  workflow_dispatch:

workflow_call:
  secrets:
      required:
      - SSH_PRIVATE_KEY
      - DOCKER_REGISTRY
      - DOCKER_NAMESPACE

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploy dev/stg
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 zhoujie@home.starworks.cc << 'EOF'
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats:latest
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats-be:latest
            cd chats
            sed -i "s/^FRONTEND_VERSION=.*/FRONTEND_VERSION=latest/" ~/chats/dev.env
            sed -i "s/^BACKEND_VERSION=.*/BACKEND_VERSION=latest/" ~/chats/dev.env
            sed -i "s/^FRONTEND_VERSION=.*/FRONTEND_VERSION=latest/" ~/chats/stg.env
            sed -i "s/^BACKEND_VERSION=.*/BACKEND_VERSION=latest/" ~/chats/stg.env
            ./dev.sh && ./stg.sh