name: Deploy
on:
  workflow_run:
    workflows: ["Build Container", "Build BE Container"]
    types:
      - completed
    branches:
      - main
    paths:
      - 'src/FE/**'
      - 'src/BE/**'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: take a look
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 zhoujie@home.starworks.cc << 'EOF'
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats:latest
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/chats-be:latest
            cd chats
            sed -i "s/^FRONTEND_VERSION=.*/FRONTEND_VERSION=latest/" ~/chats/dev.env
            sed -i "s/^BACKEND_VERSION=.*/BACKEND_VERSION=latest/" ~/chats/dev.env
            sed -i "s/^FRONTEND_VERSION=.*/FRONTEND_VERSION=latest/" ~/chats/stg.env
            sed -i "s/^BACKEND_VERSION=.*/BACKEND_VERSION=latest/" ~/chats/stg.env
            ./dev.sh && ./stg.sh