name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
    inputs:
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_NAMESPACE:
        type: string
        required: true
      TAG:
        type: string
        required: true
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploy dev/stg
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 zhoujie@home.starworks.cc << 'EOF'
            docker pull ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_NAMESPACE }}/chats:${{ inputs.TAG }}
            cd chats
            sed -i "s/^TAG=.*/TAG=${{ inputs.TAG }}/" ~/chats/dev.env
            sed -i "s/^TAG=.*/TAG=${{ inputs.TAG }}/" ~/chats/stg.env
            ./dev.sh && ./stg.sh
            